export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "brand-pink": "#e51152",
        "brand-yellow": "#f7e600",
        "bg-primary": "var(--bg-primary)",
        "bg-secondary": "var(--bg-secondary)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "border-primary": "var(--border-primary)",
        "surface-container-highest": "#e2e2e2",
        "surface-container": "#eeeeee",
        "on-primary-fixed-variant": "#910030",
        "tertiary": "#5c5c5c",
        "on-error": "#ffffff",
        "surface-container-high": "#e8e8e8",
        "on-secondary-fixed-variant": "#4e4800",
        "on-primary-fixed": "#400010",
        "on-secondary-fixed": "#1f1c00",
        "tertiary-fixed-dim": "#c6c6c6",
        "error": "#ba1a1a",
        "primary-container": "#e51152",
        "tertiary-container": "#747474",
        "surface-bright": "#f9f9f9",
        "surface-tint": "#bd0041",
        "surface-dim": "#dadada",
        "on-primary": "#ffffff",
        "primary-fixed": "#ffd9dc",
        "inverse-surface": "#2f3131",
        "secondary-fixed": "#f7e600",
        "surface-variant": "#e2e2e2",
        "outline": "#906e71",
        "on-surface-variant": "#5c3f42",
        "on-surface": "#1a1c1c",
        "inverse-on-surface": "#f1f1f1",
        "inverse-primary": "#ffb2ba",
        "on-tertiary-fixed": "#1b1b1b",
        "on-primary-container": "#fffbff",
        "outline-variant": "#e5bdc0",
        "on-tertiary": "#ffffff",
        "background": "#f9f9f9",
        "surface": "#f9f9f9",
        "primary": "#b9003f",
        "on-secondary-container": "#6c6400",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#d8ca00",
        "on-tertiary-fixed-variant": "#474747",
        "secondary-container": "#f3e300",
        "on-background": "#1a1c1c",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#e2e2e2",
        "on-secondary": "#ffffff",
        "secondary": "#676000",
        "on-tertiary-container": "#fcfcfc",
        "primary-fixed-dim": "#ffb2ba",
        "error-container": "#ffdad6",
        "surface-container-low": "#f3f3f3"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Manrope"],
        "label": ["Space Grotesk"]
      },
      borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
